version: "3"
services:
  sagemaker-notebook-container:
    image: dataquadrant/sagemaker-notebook:python3
    container_name: sagemaker-notebook-container
    ports:
      - 8888:8888
    environment:
      AWS_PROFILE: "default-api"
    volumes:
      - ~/.aws:/home/ec2-user/.aws:ro                                # For AWS Credentials
      - ~/.ssh:/home/ec2-user/.ssh:ro                                # For Git Credentials
      - /var/run/docker.sock:/var/run/docker.sock:ro                 # For Docker CLI
      - /Users/foobar/projects/SageMaker:/home/ec2-user/SageMaker    # For saving work in a host directory
      # - .:/home/ec2-user/SageMaker/sagemaker-notebook-container    # For testing
